import type { FC } from "react";
import { graphql, useLazyLoadQuery } from "react-relay";
import { UserAvatar } from "./user-avatar";

// This import is generated by the Relay compiler after you run it.
// It gives you full TypeScript types for the query result.
// The name follows the convention: page filename + "Query"
import type { homePageContentQuery } from "@/__generated__/homePageContentQuery.graphql";

// The graphql tag is NOT a runtime function — it's a marker for the Relay compiler.
// The compiler reads this, validates it against schema.graphql, and generates:
//   1. The actual query text sent to the server
//   2. TypeScript types for the response
// You must run `yarn relay` after writing/changing any graphql`` tag.
const MeQuery = graphql`
  query homePageContentQuery {
    me {
      id
      email
      unreadMessageCount
      # Spread the fragment — Relay composes the selects automatically.
      # The compiler ensures UserAvatar's data requirements are fetched
      # as part of this query, not separately.
      ...userAvatarFragment
    }
  }
`;

const HomePageContent: FC = () => {
  // useLazyLoadQuery sends the query when this component mounts.
  // It SUSPENDS (throws a Promise) until data arrives —
  // that's why the parent needs a <Suspense> boundary.
  // The second argument is variables — empty object since me() takes none.
  const data = useLazyLoadQuery<homePageContentQuery>(MeQuery, {});

  // data.me is typed exactly from your GraphQL schema —
  // nullable because the query returns null when not logged in
  if (!data.me) {
    return <div>Not logged in</div>;
  }

  const user = data.me;

  return (
    <div>
      {/* Pass the fragment ref — NOT the whole data object.
          Relay enforces that UserAvatar only sees what it declared. */}
      <UserAvatar user={user} />
      <p>ID: {user.id}</p>
      <p>Email: {user.email}</p>
      <p>Unread: {user.unreadMessageCount}</p>
    </div>
  );
};

export default HomePageContent;
