import type { FC } from "react";
import { graphql, useFragment } from "react-relay";
import type { userAvatarFragment$key } from "@/__generated__/userAvatarFragment.graphql";

// This fragment declares what UserAvatar needs from a User
// The $key type is generated by the Relay compiler
const UserAvatarFragment = graphql`
  fragment userAvatarFragment on User {
    displayName
    username
    profile {
      avatar
    }
  }
`;

type UserAvatarProps = {
  // The parent passes a "fragment ref" — an opaque reference to the data.
  // UserAvatar doesn't know or care where the data came from.
  user: userAvatarFragment$key;
};

export const UserAvatar: FC<UserAvatarProps> = ({ user }) => {
  // useFragment reads data from the ref — zero network request
  const data = useFragment(UserAvatarFragment, user);

  return (
    <div>
      {data.profile?.avatar && (
        <img src={data.profile.avatar} alt={data.displayName ?? ""} />
      )}
      <span>{data.displayName ?? data.username}</span>
    </div>
  );
};
