
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Permission
 * Permission is just a named capability. The name follows a pattern you defined:
 * category:action:scope (e.g. message:delete:any, user:edit:own). Nothing more
 * it's a record that says "this capability exists."
 */
export type Permission = Prisma.PermissionModel
/**
 * Model Role
 * Role is a named group of permissions. A user belongs to exactly one role
 */
export type Role = Prisma.RoleModel
/**
 * Model RolePermission
 * This is a join table between Role and Permission. Nothing fancy.
 */
export type RolePermission = Prisma.RolePermissionModel
/**
 * Model UserPermission
 * This is the hybrid part. The grantedById field is doing double duty:
 * 
 * If it has a value → this permission was explicitly granted directly to this user by an admin
 * If it's null → this permission is explicitly revoked from this user
 */
export type UserPermission = Prisma.UserPermissionModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Follow
 * 
 */
export type Follow = Prisma.FollowModel
/**
 * Model Profile
 * 
 */
export type Profile = Prisma.ProfileModel
/**
 * Model Message
 * 
 */
export type Message = Prisma.MessageModel
