
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 * 
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
export * from "./enums.ts"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Permissions
 * const permissions = await prisma.permission.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }


// file annotations for bundling tools to include these files
path.join(__dirname, "query_engine-windows.dll.node")
path.join(process.cwd(), "src/lib/prisma/query_engine-windows.dll.node")

/**
 * Model Permission
 * Permission is just a named capability. The name follows a pattern you defined:
 * category:action:scope (e.g. message:delete:any, user:edit:own). Nothing more
 * it's a record that says "this capability exists."
 */
export type Permission = Prisma.PermissionModel
/**
 * Model Role
 * Role is a named group of permissions. A user belongs to exactly one role
 */
export type Role = Prisma.RoleModel
/**
 * Model RolePermission
 * This is a join table between Role and Permission. Nothing fancy.
 */
export type RolePermission = Prisma.RolePermissionModel
/**
 * Model UserPermission
 * This is the hybrid part. The grantedById field is doing double duty:
 * 
 * If it has a value → this permission was explicitly granted directly to this user by an admin
 * If it's null → this permission is explicitly revoked from this user
 */
export type UserPermission = Prisma.UserPermissionModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Follow
 * 
 */
export type Follow = Prisma.FollowModel
/**
 * Model Profile
 * 
 */
export type Profile = Prisma.ProfileModel
/**
 * Model Message
 * 
 */
export type Message = Prisma.MessageModel
